---
title: "README"
author: "Matt Noone"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  github_document:
    toc: yes
always_allow_html: yes
urlcolor: blue
css: "./inst/app/www/stye.css"
---

```{r setup, include=FALSE, eval = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = F, warning = F)

```

## Overview

Growing Shade is a new tool for improving the equity and sustainability of the Dane County region through tree canopy enhancement and preservation. Equity and sustainability are two goals of Dane County which Growing Shade makes actionable. Growing Shade can be accessed at: *****. 

Growing Shade is predicated on the fact that trees help the region thrive. Benefits from trees include cooler temperatures, improved air quality, cleaner storm water, improved mental health, and enhanced biodiversity. Enhancing and preserving tree canopy cover is an actionable step to create healthy and resilient places. 

Trees additionally connect to regional issues and priorities. Public health, environmental justice, climate change, and natural resource conservation all intersect with the tree canopy. Growing Shade provides tree planting efforts and ongoing maintenance with new perspectives, rigorous science, and thoughtful synthesis. 

Growing Shade combines local **stories** and an **interactive mapping tool** to inform tree canopy enhancement and preservation. 

**This repository walks through the creation and aggregation of data used in interactive mapping tool.**

## Scaling to other regions

The original fork for this project was developed by Ellen Esch of the Twin Cities, Minnesota region. See the original repository here:
https://github.com/Metropolitan-Council/planting.shade

## Evolution of the project

Growing shade concept is a merger of:

- Fundamental ecological principles coupled with remote sensing (for technical tree parameters, data, and metrics)
- Conversations with advisory group for Growing Shade Project (for concept and framing)
- The Economic Values Atlas project in collaboration with Brookings Institution (for methods of synthesizing demographic data)


